<Process id="97f1e48d-0f0c-4c63-be1e-a9053b8ee3dc" type="task" workType="foreground" name="T_test" version="" designerVersion="3.1.100.11228" lastPublishedServer="" readonly="false" isValid="false" DesignedBy="Designer" Template="" StepCount="2" Orientation="horizontal">
  <Properties>
    <Property key="Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" enabled="True" />
    <Property key="onBefore" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" enabled="True" />
    <Property key="onAfter" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" enabled="True" />
    <Property key="onError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" enabled="True" />
    <Property key="Timeout" controlType="Int32" valueType="System.Int32" formatType="Integer" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="0" />
    <Property key="RunningTime" controlType="Int32" valueType="System.Int32" formatType="Integer" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="5" />
    <Property key="Os" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="Microsoft Windows 10 Pro64비트" />
    <Property key="Resolution" controlType="String" valueType="System.String" formatType="String_Size" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="1920x1200" />
    <Property key="CreatedDate" controlType="String" valueType="System.String" formatType="String_DateTime" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="2024-07-08 12:16:10" />
    <Property key="CreatedBy" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
    <Property key="LastModifiedDate" controlType="String" valueType="System.String" formatType="String_DateTime" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="2024-07-08 13:45:15" />
    <Property key="LastModifiedBy" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="" />
    <Property key="LastPublishedDate" controlType="String" valueType="System.String" formatType="String_DateTime" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
    <Property key="LastPublishedBy" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
  </Properties>
  <LinkItems />
  <Variables />
  <Steps>
    <Step id="Sf4fbe78fdd0847ac8d0c0e6ce067b0a7" ver="311231130" createVer="311231130" type="Net" name="OpenBrowser" dpName="OpenBrowser" dpValue="https://map.kakao.com/" dpValue2="" dpImage="" tag="" depth="1" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="299a43b5-59a5-43ad-9506-ec79fc8218ad" type="Net">
        <Property type="Net" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Net" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Net" key="HTML_BrowserID" controlType="OutputControlType" valueType="System.Object" formatType="Variable" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="RESULT" />
        <Property type="Net" key="HTML_URL" controlType="String" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="'https://map.kakao.com/'" />
        <Property type="Net" key="HTML_Maximize" controlType="Boolean" valueType="System.Boolean" formatType="Boolean" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="True" />
        <Property type="Net" key="HTML_WaitTimeSec" controlType="Int32" valueType="System.Int32" formatType="Integer" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="10" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[RESULT = StepPlayer.Run('Net.OpenBrowser', this.openbrowser_info_1);]]></Script>
    </Step>
    <Step id="S53d4ede0a6f0417988a8c2f95c09e3da" ver="311231130" createVer="311231130" type="Flow" name="Debugger" dpName="Debugger" dpValue="RESULT" dpValue2="" dpImage="" tag="" depth="1" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="3b8d3279-968d-49a7-8f9d-01a61201b2ac" type="Flow">
        <Property type="Flow" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_Message" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="RESULT" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[OpenDebugger(RESULT);]]></Script>
    </Step>
  </Steps>
  <JScript><![CDATA[function T_test() {

    this.RPAGOTOENABLE = false;
    this.GotoStepRetryCntMap = {};
    this.GotoBlockMap = {};
    this.GotoReverseBlockMap = {};
    this.GotoStepBlockTypeMap = {};


    this.run = function() {

        //------------------------------------------------
        STEP('Sf4fbe78fdd0847ac8d0c0e6ce067b0a7', '[1] OpenBrowser');
        RESULT = StepPlayer.Run('Net.OpenBrowser', this.openbrowser_info_1);

        //------------------------------------------------
        STEP('S53d4ede0a6f0417988a8c2f95c09e3da', '[2] Debugger');
        OpenDebugger(RESULT);


    }

    this.execute = function() {
        var result = null;
        result = this.run()
        if (result != null)
            return result;
    }
}
]]></JScript>
  <Diagram version="1.300" nodesize="Normal">
    <StepNodes>
      <StepNode step_id="Sf4fbe78fdd0847ac8d0c0e6ce067b0a7" group_name="39ec8996-066c-4182-8b38-e63c2155200c_Untitled" folded="False" color="" />
      <StepNode step_id="S53d4ede0a6f0417988a8c2f95c09e3da" group_name="39ec8996-066c-4182-8b38-e63c2155200c_Untitled" folded="False" color="" />
    </StepNodes>
  </Diagram>
</Process>