<Process id="83999f66-1d04-4b58-a072-cb93f73c9d3d" type="task" workType="foreground" name="T_test03" version="" designerVersion="3.1.100.11228" lastPublishedServer="" readonly="false" isValid="false" DesignedBy="Designer" Template="" StepCount="7" Orientation="horizontal">
  <Properties>
    <Property key="Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" enabled="True" />
    <Property key="onBefore" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" enabled="True" />
    <Property key="onAfter" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" enabled="True" />
    <Property key="onError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" enabled="True" />
    <Property key="Timeout" controlType="Int32" valueType="System.Int32" formatType="Integer" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="0" />
    <Property key="RunningTime" controlType="Int32" valueType="System.Int32" formatType="Integer" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="9" />
    <Property key="Os" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="Microsoft Windows 10 Pro64비트" />
    <Property key="Resolution" controlType="String" valueType="System.String" formatType="String_Size" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="1920x1200" />
    <Property key="CreatedDate" controlType="String" valueType="System.String" formatType="String_DateTime" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="2024-07-09 09:51:02" />
    <Property key="CreatedBy" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
    <Property key="LastModifiedDate" controlType="String" valueType="System.String" formatType="String_DateTime" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="2024-07-09 09:55:27" />
    <Property key="LastModifiedBy" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="" />
    <Property key="LastPublishedDate" controlType="String" valueType="System.String" formatType="String_DateTime" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
    <Property key="LastPublishedBy" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
  </Properties>
  <LinkItems />
  <Variables>
    <Variable name="inputNum" scope="Normal" valueType="Any" formatType="Any" initValue="" desc="" colorValue="#FF617143" showMarker="False" />
  </Variables>
  <Steps>
    <Step id="S18a4ab6de1d544a6be3d85e5a1000cdb" ver="311231130" createVer="311231130" type="Desktop" name="InputBox" dpName="InputBox" dpValue="this.inputNum" dpValue2="" dpImage="" tag="" depth="1" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="52d3a06b-cd15-4dca-9d33-73babe6d374c" type="Desktop">
        <Property type="Desktop" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Desktop" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Desktop" key="Conditions_Variable" controlType="OutputControlType" valueType="System.Object" formatType="Variable" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="this.inputNum" />
        <Property type="Desktop" key="Conditions_PromptType" controlType="PropertyItemDropDownView" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="Text" valuelist="OK;OK/Cancel;Yes/No;Yes/No/Cancel;Abort/Retry/Ignore;Retry/Cancel;Text" />
        <Property type="Desktop" key="Conditions_DefaultValue" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="''" />
        <Property type="Desktop" key="Conditions_DefaultItem" controlType="String" valueType="System.String" formatType="String" required="False" visible="False" readonly="False" encrypted="False" isChanged="N" value="''" />
        <Property type="Desktop" key="Conditions_PromptMessage" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="''" />
        <Property type="Desktop" key="Conditions_TimeoutSec" controlType="Int32" valueType="System.Int32" formatType="Integer" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="600" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[this.inputNum = InputBox('','Text', '', 600);]]></Script>
    </Step>
    <Step id="S22c1fc1027164f75bb8500a63f8ae902" ver="311231130" createVer="311231130" type="Flow" name="DecisionThen" dpName="IfThen" dpValue="this.inputNum==1" dpValue2="" dpImage="" tag="" depth="1" stmttype="OpenBlock" enabled="True" mainSet="0">
      <Properties id="9c091d9d-9a4b-45fd-b612-730ff0d3210c" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_Expression" controlType="PropertyItemTextEditorView" valueType="System.Object" formatType="Condition" required="True" visible="False" readonly="True" encrypted="False" isChanged="N" value="this.inputNum==1" order="1" />
        <Property type="Flow" key="Conditions_CombineCondition" controlType="PropertyItemCombineConditionView" valueType="System.Boolean" formatType="Boolean" required="False" visible="False" readonly="False" encrypted="False" isChanged="N" value="True" order="2" />
        <Property type="Flow" key="Conditions_Expression1" controlType="PropertyItemExpressionView" valueType="System.Object" formatType="Condition" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="this.inputNum==1" order="3" />
        <Property type="Flow" key="Conditions_AddCondition" controlType="PropertyItemAddConditionView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
      </Properties>
      <RelatedSteps>
        <RelatedStep id="S91baefede6674995b48bcd78c1f7c13d" type="Flow" name="EndDecisionThen" />
      </RelatedSteps>
      <Script><![CDATA[if (this.inputNum==1) {]]></Script>
    </Step>
    <Step id="Sa5e2549e9b73450ba0609800505028fe" ver="311231130" createVer="311231130" type="Win" name="OpenApp" dpName="OpenApp" dpValue="notepad" dpValue2="" dpImage="" tag="" depth="2" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="ab6239c2-8b01-4915-b1d4-32b9a8fb80c2" type="Win">
        <Property type="Win" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Win" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Win" key="Application_PID" controlType="OutputControlType" valueType="System.Int32" formatType="Variable" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="RESULT" />
        <Property type="Win" key="Application_Command" controlType="String" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="'notepad'" />
        <Property type="Win" key="Application_Arguments" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="''" />
        <Property type="Win" key="Application_DerivedApp" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="''" />
        <Property type="Win" key="Options_Maximize" controlType="Boolean" valueType="System.Boolean" formatType="Boolean" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="False" />
        <Property type="Win" key="Options_WaitTimeSec" controlType="Int32" valueType="System.Int32" formatType="Integer" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="5" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[RESULT = WinApplicationPlayer.OpenApp('notepad', '', false, 5, '');]]></Script>
    </Step>
    <Step id="S91baefede6674995b48bcd78c1f7c13d" ver="311231130" createVer="311231130" type="Flow" name="EndDecisionThen" dpName="End-IfThen" dpValue="" dpValue2="" dpImage="" tag="" depth="2" stmttype="CloseBlock" enabled="True" mainSet="0">
      <Properties id="7f91f391-3207-418b-b800-923012a09ebc" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
      </Properties>
      <RelatedSteps>
        <RelatedStep id="S22c1fc1027164f75bb8500a63f8ae902" type="Flow" name="DecisionThen" />
      </RelatedSteps>
      <Script><![CDATA[}]]></Script>
    </Step>
    <Step id="Sbd450220d6104881b61319eb2de34907" ver="311231130" createVer="311231130" type="Flow" name="DecisionThen" dpName="IfThen" dpValue="this.inputNum==2" dpValue2="" dpImage="" tag="" depth="1" stmttype="OpenBlock" enabled="True" mainSet="0">
      <Properties id="abc7d6d2-c216-42de-abd4-4b60cb77a2d6" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_Expression" controlType="PropertyItemTextEditorView" valueType="System.Object" formatType="Condition" required="True" visible="False" readonly="True" encrypted="False" isChanged="N" value="this.inputNum==2" order="1" />
        <Property type="Flow" key="Conditions_CombineCondition" controlType="PropertyItemCombineConditionView" valueType="System.Boolean" formatType="Boolean" required="False" visible="False" readonly="False" encrypted="False" isChanged="N" value="True" order="2" />
        <Property type="Flow" key="Conditions_Expression1" controlType="PropertyItemExpressionView" valueType="System.Object" formatType="Condition" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="this.inputNum==2" order="3" />
        <Property type="Flow" key="Conditions_AddCondition" controlType="PropertyItemAddConditionView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
      </Properties>
      <RelatedSteps>
        <RelatedStep id="S45120b849b09421084a19d8451f5011b" type="Flow" name="EndDecisionThen" />
      </RelatedSteps>
      <Script><![CDATA[if (this.inputNum==2) {]]></Script>
    </Step>
    <Step id="S0974e9afb7bc4494869ca348c8a4b272" ver="311231130" createVer="311231130" type="Win" name="OpenApp" dpName="OpenApp" dpValue="chrome" dpValue2="" dpImage="" tag="" depth="2" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="c56e0c7a-5b3f-4374-810b-e57b20d45efb" type="Win">
        <Property type="Win" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Win" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Win" key="Application_PID" controlType="OutputControlType" valueType="System.Int32" formatType="Variable" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="RESULT" />
        <Property type="Win" key="Application_Command" controlType="String" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="'chrome'" />
        <Property type="Win" key="Application_Arguments" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="''" />
        <Property type="Win" key="Application_DerivedApp" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="''" />
        <Property type="Win" key="Options_Maximize" controlType="Boolean" valueType="System.Boolean" formatType="Boolean" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="False" />
        <Property type="Win" key="Options_WaitTimeSec" controlType="Int32" valueType="System.Int32" formatType="Integer" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="5" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[RESULT = WinApplicationPlayer.OpenApp('chrome', '', false, 5, '');]]></Script>
    </Step>
    <Step id="S45120b849b09421084a19d8451f5011b" ver="311231130" createVer="311231130" type="Flow" name="EndDecisionThen" dpName="End-IfThen" dpValue="" dpValue2="" dpImage="" tag="" depth="2" stmttype="CloseBlock" enabled="True" mainSet="0">
      <Properties id="6881c091-af43-4b1a-93ba-b06289014021" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
      </Properties>
      <RelatedSteps>
        <RelatedStep id="Sbd450220d6104881b61319eb2de34907" type="Flow" name="DecisionThen" />
      </RelatedSteps>
      <Script><![CDATA[}]]></Script>
    </Step>
  </Steps>
  <JScript><![CDATA[function T_test03() {

    this.inputNum;

    this.RPAGOTOENABLE = false;
    this.GotoStepRetryCntMap = {};
    this.GotoBlockMap = {2:[4],5:[7]};
    this.GotoReverseBlockMap = {4:2,7:5};
    this.GotoStepBlockTypeMap = {2:'DecisionThen',4:'EndDecisionThen',5:'DecisionThen',7:'EndDecisionThen'};


    this.run = function() {

        //------------------------------------------------
        STEP('S18a4ab6de1d544a6be3d85e5a1000cdb', '[1] InputBox');
        this.inputNum = InputBox('','Text', '', 600);

        //------------------------------------------------
        STEP('S22c1fc1027164f75bb8500a63f8ae902', '[2] IfThen');
        if (this.inputNum==1) {

            //------------------------------------------------
            STEP('Sa5e2549e9b73450ba0609800505028fe', '[3] OpenApp');
            RESULT = WinApplicationPlayer.OpenApp('notepad', '', false, 5, '');

        //------------------------------------------------
        }
        STEP('S91baefede6674995b48bcd78c1f7c13d', '[4] End-IfThen');

        //------------------------------------------------
        STEP('Sbd450220d6104881b61319eb2de34907', '[5] IfThen');
        if (this.inputNum==2) {

            //------------------------------------------------
            STEP('S0974e9afb7bc4494869ca348c8a4b272', '[6] OpenApp');
            RESULT = WinApplicationPlayer.OpenApp('chrome', '', false, 5, '');

        //------------------------------------------------
        }
        STEP('S45120b849b09421084a19d8451f5011b', '[7] End-IfThen');


    }

    this.execute = function() {
        var result = null;
        result = this.run()
        if (result != null)
            return result;
    }
}
]]></JScript>
  <Diagram version="1.300" nodesize="Normal">
    <StepNodes>
      <StepNode step_id="S18a4ab6de1d544a6be3d85e5a1000cdb" group_name="9d74fc41-43b7-4ac9-927e-6f32659972ef_Untitled" folded="False" color="" />
      <StepNode step_id="S22c1fc1027164f75bb8500a63f8ae902" group_name="" folded="False" color="" />
      <StepNode step_id="Sa5e2549e9b73450ba0609800505028fe" group_name="4784465e-0e85-4d7c-84cb-ba632945a254_Untitled" folded="False" color="" />
      <StepNode step_id="S91baefede6674995b48bcd78c1f7c13d" group_name="" folded="False" color="" />
      <StepNode step_id="Sbd450220d6104881b61319eb2de34907" group_name="" folded="False" color="" />
      <StepNode step_id="S0974e9afb7bc4494869ca348c8a4b272" group_name="d968e136-aec1-436d-8aa9-3673b7c0e672_Untitled" folded="False" color="" />
      <StepNode step_id="S45120b849b09421084a19d8451f5011b" group_name="" folded="False" color="" />
    </StepNodes>
  </Diagram>
</Process>