<Process id="f76fd0ff-c2ce-4762-abc9-a297ef9017b5" type="process" workType="foreground" name="P_Test" version="" designerVersion="3.1.100.11228" lastPublishedServer="" readonly="false" isValid="true" DesignedBy="Designer" Template="" StepCount="2" Orientation="horizontal">
  <Properties>
    <Property key="Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="default process" enabled="True" />
    <Property key="onBefore" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" enabled="True" />
    <Property key="onAfter" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" enabled="True" />
    <Property key="onError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" enabled="True" />
    <Property key="Timeout" controlType="Int32" valueType="System.Int32" formatType="Integer" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="0" />
    <Property key="RunningTime" controlType="Int32" valueType="System.Int32" formatType="Integer" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="0" />
    <Property key="Os" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="Microsoft Windows 10 Pro64비트" />
    <Property key="Resolution" controlType="String" valueType="System.String" formatType="String_Size" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="1920x1200" />
    <Property key="CreatedDate" controlType="String" valueType="System.String" formatType="String_DateTime" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="2024-07-05 10:06:30" />
    <Property key="CreatedBy" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
    <Property key="LastModifiedDate" controlType="String" valueType="System.String" formatType="String_DateTime" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="2024-07-05 15:05:22" />
    <Property key="LastModifiedBy" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="" />
    <Property key="LastPublishedDate" controlType="String" valueType="System.String" formatType="String_DateTime" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
    <Property key="LastPublishedBy" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
  </Properties>
  <LinkItems />
  <Variables />
  <Steps>
    <Step id="Sf90375cb3d794bdab872f2664b81075f" ver="311231130" createVer="311231130" type="Flow" name="RunTask" dpName="RunTask" dpValue="" dpValue2="" dpImage="" tag="" depth="1" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="90c3577f-aea6-4413-a68a-9fe90ba5b657" type="Flow">
        <Property type="Flow" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_TaskName" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="T_test1" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[RunTask(this, 'T_test1', null);]]></Script>
    </Step>
    <Step id="Sda337f461477415aa576f7e1e7b8649e" ver="311231130" createVer="311231130" type="Flow" name="RunTask" dpName="RunTask" dpValue="" dpValue2="" dpImage="" tag="" depth="1" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="ea7b2f5d-2793-46dc-8f4c-2acd690cfa23" type="Flow">
        <Property type="Flow" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_TaskName" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="T_test2" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[RunTask(this, 'T_test2', null);]]></Script>
    </Step>
  </Steps>
  <JScript><![CDATA[function P_Test() {

    this.RPAGOTOENABLE = false;
    this.GotoStepRetryCntMap = {};
    this.GotoBlockMap = {};
    this.GotoReverseBlockMap = {};
    this.GotoStepBlockTypeMap = {};


    this.run = function() {

        //------------------------------------------------
        STEP('Sf90375cb3d794bdab872f2664b81075f', '[1] RunTask');
        RunTask(this, 'T_test1', null);

        //------------------------------------------------
        STEP('Sda337f461477415aa576f7e1e7b8649e', '[2] RunTask');
        RunTask(this, 'T_test2', null);


    }

    this.execute = function() {
        var result = null;
        result = this.run()
        if (result != null)
            return result;
    }
}
]]></JScript>
  <Diagram version="1.300" nodesize="Normal">
    <StepNodes>
      <StepNode step_id="Sf90375cb3d794bdab872f2664b81075f" group_name="" folded="False" color="" />
      <StepNode step_id="Sda337f461477415aa576f7e1e7b8649e" group_name="" folded="False" color="" />
    </StepNodes>
  </Diagram>
</Process>